# Site settings
title: Devon Grove | Software Developer
description: Devon Grove | Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.devongrove.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Devon Grove
user_description: Web Developer
user_title: Software Developer
email: devon.j.grove@gmail.com
twitter_username: devongroveweb
github_username:  djgrove
linkedin_username: devongrove
disqus_username: devongrove

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Tags
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
